version: 0.0
os: linux
files:
  - source: /public
    destination: /var/www/html/ejt/public
permissions:
  - object: /var/www/html/ejt
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
